language: swift
osx_image: xcode10
xcode_workspace: BayPass.xcworkspace
xcode_scheme: BayPass
xcode_sdk: iphonesimulator

before_install:
- pod update
install:
  - bundle install
script:
  - fastlane ios test
  
notifications:
     slack: dattworkspace:dOHdcFiG3BrlqZC0zbzXmZiX