language: swift
osx_image: xcode10

before_install:
  - pod update
script:
  - set -o pipefail && xcodebuild -workspace BayPass.xcworkspace -scheme BayPass -sdk iphonesimulator -enableCodeCoverage YES build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
     slack: dattworkspace:dOHdcFiG3BrlqZC0zbzXmZiX