language: swift
osx_image: xcode10.1

before_install:
- pod update
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace BayPass.xcworkspace -scheme BayPass -sdk iphonesimulator12.1 | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BayPass'

notifications:
     slack: dattworkspace:dOHdcFiG3BrlqZC0zbzXmZiX
